services:
  mysqldb:
    image: mysql:8.0.25
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: taphoait
      MYSQL_DATABASE: taphoait
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - '3307:3306'
    volumes:
      - ./src/main/resources/database:/docker-entrypoint-initdb.d/

