spring:
  mail:
    host: smtp.gmail.com
    from: ${MAIL_FROM}
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true