spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:"YOUR EMAIL"}
            client-secret: ${GOOGLE_CLIENT_SECRET:"YOUR KEY"}
            scope:
              - email
              - profile
              - openid
            redirect-uri: http://localhost:8080/login/oauth2/authorization/google
            authorization-grant-type: authorization_code